# Generated by Django 3.0.7 on 2020-06-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Pagina', 'verbose_name_plural': 'Paginas'},
        ),
    ]
